name: Run License Tests
on:
  push:
  workflow_dispatch:

jobs:
  license_tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Install core repo
        run: |
          pip install .
      - name: Get explicit and transitive dependencies
        run: |
          pip freeze > requirements-all.txt
      - name: Check python
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v0.5.0
        with:
          requirements: 'requirements-all.txt'
          fail: 'Copyleft,Other,Error'
          fails-only: true
          exclude-license: '^(Mozilla).*$'
      - name: Print report
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}"